### ISSUE TITLE
Storages with OperationError state should be excluded from vshard config

### ISSUE THREAD

**Issue by olegrok** [tarantool/cartridge#1411]
Since vshard doesn't know anything about cartridge state machine we could have a case when
vshard makes requests to instance with OperationError state. It looks wrong and unclear for customers.

**Comment by rosik** [comment]
We've recently discussed a similar problem with @sharonovd, but it was about the `RecoveringSnapshot` state.

It sounds like you need an "automatic disable" feature, but it may be dangerous.

**Comment by sergos** [comment]
Router will check the replies from a storage and in case of error will redirect the request automatically. 
Details are https://github.com/tarantool/vshard/issues/298

**Comment by sergos** [comment]
The tarantool/vshard#298 is fixed, need to verify the problem is resolved.

**Comment by olegrok** [comment]
> The [tarantool/vshard#298](https://github.com/tarantool/vshard/issues/298) is fixed, need to verify the problem is resolved.

It's not resolved. Because vshard doesn't know anything about cartridge.

Steps to fix an issue:
  - Release new vshard
  - Update vshard version in cartridge
  - Add vshard.storage.disable() when instance switches to the state to OperationError
  - Cover this case with test

**Comment by filonenko-mikhail** [comment]
Related blockers

https://github.com/tarantool/vshard/issues/311

https://github.com/tarantool/vshard/issues/310
